//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.dengzhiguo.eread.activity.actions;

import android.content.Context;
import cn.dengzhiguo.eread.bo.BookImpl_;

public final class InitAction_
    extends InitAction
{

    private Context context_;

    private InitAction_(Context context) {
        context_ = context;
        init_();
    }

    public static InitAction_ getInstance_(Context context) {
        return new InitAction_(context);
    }

    private void init_() {
        book = BookImpl_.getInstance_(context_);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
