//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.dengzhiguo.eread.activity.actions;

import android.content.Context;
import cn.dengzhiguo.eread.bo.BookImpl_;

public final class ListBookAction_
    extends ListBookAction
{

    private Context context_;

    private ListBookAction_(Context context) {
        context_ = context;
        init_();
    }

    public static ListBookAction_ getInstance_(Context context) {
        return new ListBookAction_(context);
    }

    private void init_() {
        book = BookImpl_.getInstance_(context_);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
