//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.dengzhiguo.eread.activity.actions;

import android.content.Context;

public final class PlayVoiceAction_
    extends PlayVoiceAction
{

    private Context context_;

    private PlayVoiceAction_(Context context) {
        context_ = context;
        init_();
    }

    public static PlayVoiceAction_ getInstance_(Context context) {
        return new PlayVoiceAction_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
