//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.dengzhiguo.eread.activity.actions;

import android.content.Context;
import cn.dengzhiguo.eread.bo.BookImpl_;

public final class SaveBookAction_
    extends SaveBookAction
{

    private Context context_;

    private SaveBookAction_(Context context) {
        context_ = context;
        init_();
    }

    public static SaveBookAction_ getInstance_(Context context) {
        return new SaveBookAction_(context);
    }

    private void init_() {
        bookBo = BookImpl_.getInstance_(context_);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
