//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.dengzhiguo.eread.activity.actions;

import android.content.Context;
import cn.dengzhiguo.eread.net.DictNetHandler_;

public final class TranslateAction_
    extends TranslateAction
{

    private Context context_;

    private TranslateAction_(Context context) {
        context_ = context;
        init_();
    }

    public static TranslateAction_ getInstance_(Context context) {
        return new TranslateAction_(context);
    }

    private void init_() {
        dictHandler = DictNetHandler_.getInstance_(context_);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
