//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.dengzhiguo.eread.adapter;

import android.content.Context;

public final class BookListAdapter_
    extends BookListAdapter
{

    private Context context_;

    private BookListAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static BookListAdapter_ getInstance_(Context context) {
        return new BookListAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
