//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.dengzhiguo.eread.net;

import java.util.HashMap;
import cn.dengzhiguo.eread.modal.TranslateInfo;
import org.androidannotations.api.rest.RestErrorHandler;
import org.springframework.http.HttpMethod;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

public final class DictClient_
    implements DictClient
{

    private String rootUrl;
    private RestTemplate restTemplate;
    private RestErrorHandler restErrorHandler;

    public DictClient_() {
        rootUrl = "http://dict-co.iciba.com/api/";
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new MyJacksonConverter());
    }

    @Override
    public TranslateInfo getTranslate(String word) {
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("word", word);
        try {
            return restTemplate.exchange(rootUrl.concat("dictionary.php?w={word}&key=B551388316D652BEA79B45FDEA46F1C0&type=json"), HttpMethod.GET, null, TranslateInfo.class, urlVariables).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

}
