//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.dengzhiguo.eread.net;

import android.content.Context;

public final class DictNetHandler_
    extends DictNetHandler
{

    private Context context_;

    private DictNetHandler_(Context context) {
        context_ = context;
        init_();
    }

    public static DictNetHandler_ getInstance_(Context context) {
        return new DictNetHandler_(context);
    }

    private void init_() {
        dictClient = new DictClient_();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
