//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.dengzhiguo.eread.bo;

import android.content.Context;

public final class FileUtil_
    extends FileUtil
{

    private Context context_;

    private FileUtil_(Context context) {
        context_ = context;
        init_();
    }

    public static FileUtil_ getInstance_(Context context) {
        return new FileUtil_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
